language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache: npm
jobs:
  include:
    - stage: test
      node_js:
        - 10.15.3
        - 12.2.0
      skip_cleanup: 'true'
      script:
        - npm run cover
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
node_js:
  - 10.16.0
  - 12.5.0
